/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    extend: {
      colors: {
        "surface-container": "#1d2022",
        "inverse-surface": "#e0e3e5",
        "primary-fixed-dim": "#fbb3c1",
        "surface-container-lowest": "#0b0f10",
        "surface": "#101415",
        "surface-tint": "#fbb3c1",
        "primary-fixed": "#ffd9df",
        "on-background": "#e0e3e5",
        "on-surface": "#e0e3e5",
        "tertiary": "#dfe6ff",
        "on-tertiary-fixed-variant": "#3f465c",
        "outline-variant": "#514345",
        "on-primary-fixed": "#360c19",
        "surface-container-high": "#272a2c",
        "tertiary-fixed": "#dae2fd",
        "on-tertiary-container": "#4d556b",
        "on-secondary-fixed-variant": "#005227",
        "on-tertiary-fixed": "#131b2e",
        "surface-container-highest": "#323537",
        "on-secondary": "#003919",
        "outline": "#9e8c8f",
        "on-surface-variant": "#d6c2c4",
        "tertiary-container": "#c2cae4",
        "on-primary-container": "#7b4551",
        "tertiary-fixed-dim": "#bec6e0",
        "inverse-primary": "#864e5a",
        "on-error": "#690005",
        "secondary": "#4de082",
        "primary": "#ffdee3",
        "on-tertiary": "#283044",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#003e1c",
        "on-primary-fixed-variant": "#6b3743",
        "primary-container": "#ffb7c5",
        "secondary-container": "#00b55d",
        "secondary-fixed-dim": "#4de082",
        "error": "#ffb4ab",
        "surface-dim": "#101415",
        "surface-bright": "#363a3b",
        "on-primary": "#50212d",
        "secondary-fixed": "#6dfe9c",
        "surface-container-low": "#191c1e",
        "background": "#101415",
        "inverse-on-surface": "#2d3133",
        "error-container": "#93000a",
        "on-secondary-fixed": "#00210c",
        "surface-variant": "#323537",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        margin: "32px",
        sm: "12px",
        xl: "80px",
        md: "24px",
        xs: "4px",
        lg: "48px",
        gutter: "24px",
        base: "8px",
      },
      fontFamily: {
        "display-lg": ["Manrope"],
        "body-base": ["Manrope"],
        "label-caps": ["Manrope"],
        "body-sm": ["Manrope"],
        "headline-md": ["Manrope"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-base": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
